### ISSUE TITLE
DRのRDSインスタンスタイプ変更

### ISSUE THREAD

**Issue by nishida-keigo** [nexway/actions#3]
6月購入で新しいインスタンスタイプで購入するため、急ぎでインスタンスタイプを上げる

- db.m5.large → db.m6g.large
  - n2rds-dr-production-hea
  - n2rds-dr-production-bla
  - n2rds-dr-production-clk
  - n2rds-dr-production-gs
- db.t3.medium → db.t4g.medium
  - n2rds-dr-production-plus

## 備考
- トラマネで使っているため、センターさんに言ってから実施する
- リードレプリカなので、つないだままアップグレードできるか？
  - インプレースアップデートできそうなかんじ。開発で試してみる？

**Comment by nishida-keigo** [comment]
クラメソより

```
お世話になっております。
クラスメソッドオペレーションチームです。
 
お問い合わせをいただきました内容について回答をさせて頂きます。
 
【3, 質問/確認事項】

現在東京にあるRDSからシンガポールへクロスリージョンレプリケーションを使用してDBを稼働させております。

このクロスリージョンレプリケーション先のDBのインスタンスタイプを変更したいのですが、

 
お客様の環境を確認したところ、同一アカウント内で東京からシンガポールのRDSへクロスリージョンレプリケーション[1]を
ご利用中と見受けられましたが、当方の認識に齟齬がございましたらご教示ください。
 
・クロスリージョンレプリケーション中にインスタンスタイプ変更は可能か

 
はい、インスタンスタイプは任意のタイミングで変更いただけますが、変更時には再起動によるダウンタイムが発生致します。[2]
 
・変更後に、データのレプリケーションは戻るのか

 
はい、インスタンス変更後（再起動後）はレプリカインスタンスから再度同期処理が行われることが期待される挙動でございます。
 
RDS/Auroraのクロスリージョンレプリケーションはバイナリログレプリケーションにて実装されておりますため、レプリカ元の
バイナリログ保持期間中に再起動等を行なってもレプリケーションは再開されることが期待される動作になります。
 
詳細は過去に類似の問い合わせでAWSサポートに確認をした際の回答[3]をご参考いただけますでしょうか。
 
※MySQLだけでなく、Aurora MySQLもあり、そちら可能かもご教授いただきたいです。

 
Aurora MySQLでもクロスリージョンレプリケーション（バイナリログレプリケーション）の上記挙動は同一でございます。
 
■参考資料
[1]別の AWS リージョン でのリードレプリカの作成 - Amazon Relational Database Service
https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/USER_ReadRepl.XRgn.html
 
[2]DB インスタンスの設定 - Amazon Relational Database Service
https://docs.aws.amazon.com/ja_jp/AmazonRDS/latest/UserGuide/USER_ModifyInstance.Settings.html
===== 抜粋 =====
DB インスタンスクラス
（略）
この変更中に、ダウンタイムが発生します。
===== 抜粋 =====
 
[3]AWSサポートの過去回答
===== 抜粋 =====
レプリケーションマスター側のWriterのDBインスタンスが再起動されますと一時的にダウンタイムが発生し、レプリケーションのレプリカから接続ができない状態となりますが、レプリカから自動的にレプリケーションの再開が繰り返し試行されますので、通常、DBインスタンスの再起動が完了しますと自動的にレプリケーションは再開されます。
また、レプリカ側のDBインスタンスを再起動した場合にも同様に、自動的にレプリケーションの再開を試みます。
そのため、基本的にはお客様にて追加でのご対応など実施いただく必要はございませんが、万が一に備えて、DBインスタンスの再起動後のレプリカのSHOW SLAVE STATUS\Gの結果などについてはご確認いただけますと幸いです。
===== 抜粋 =====

**Comment by nishida-keigo** [comment]
## 検証

### CRR作成

- n2rds-develop-onbin-80のCRR作成
<img width="866" alt="Image" src="https://github.com/user-attachments/assets/11aa37fc-b37a-4d25-83e7-2d30d30771e7" />

<img width="843" alt="Image" src="https://github.com/user-attachments/assets/cd68a3d5-af8c-4fcb-a712-21a55386b851" />

<img width="569" alt="Image" src="https://github.com/user-attachments/assets/dc84bc30-85c9-4fb5-8652-2fafcbc83b34" />


- のCRR作成

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/f964273b-528c-4bea-ae9e-171b8dbe8a0c" />

<img width="582" alt="Image" src="https://github.com/user-attachments/assets/0f579c48-0f28-491c-be8e-9423c71eadf4" />


作成できた

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/0ca14349-b7fa-47e1-b76c-979dc49d5622" />

### レプリケーション状況確認

- n2rds-develop-onbin-80-crr

```
mysql> show replica status\G
*************************** 1. row ***************************
             Replica_IO_State: Waiting for master to send event
                  Source_Host: 172.23.1.141
                  Source_User: rdsrepladmin
                  Source_Port: 3306
                Connect_Retry: 60
              Source_Log_File: mysql-bin-changelog.004699
          Read_Source_Log_Pos: 544
               Relay_Log_File: relaylog.000020
                Relay_Log_Pos: 780
        Relay_Source_Log_File: mysql-bin-changelog.004699
           Replica_IO_Running: Yes
          Replica_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table: innodb_memcache.cache_policies,innodb_memcache.config_options,mysql.plugin,mysql.rds_configuration,mysql.rds_history,mysql.rds_monitor,mysql.rds_replication_status,mysql.rds_sysinfo,mysql.rds_upgrade_prechecks
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Source_Log_Pos: 544
              Relay_Log_Space: 1040
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Source_SSL_Allowed: Yes
           Source_SSL_CA_File:
           Source_SSL_CA_Path:
              Source_SSL_Cert:
            Source_SSL_Cipher:
               Source_SSL_Key:
        Seconds_Behind_Source: 0
Source_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Source_Server_Id: 1815583817
                  Source_UUID: f691ed42-f571-11ef-8ce5-06be67a5a0db
             Source_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
    Replica_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Source_Retry_Count: 86400
                  Source_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Source_SSL_Crl:
           Source_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Source_TLS_Version:
       Source_public_key_path:
        Get_Source_public_key: 0
            Network_Namespace:
1 row in set (0.07 sec)
```

`Seconds_Behind_Source: 0`問題なし

- n2rds-develop-plus-80-cluster-crr

```
mysql> show replica status\G
*************************** 1. row ***************************
             Replica_IO_State: Waiting for source to send event
                  Source_Host: 172.21.15.0
                  Source_User: rdsrepladmin
                  Source_Port: 3306
                Connect_Retry: 60
              Source_Log_File: mysql-bin-changelog.007754
          Read_Source_Log_Pos: 491750
               Relay_Log_File: relaylog.000009
                Relay_Log_Pos: 20449
        Relay_Source_Log_File: mysql-bin-changelog.007754
           Replica_IO_Running: Yes
          Replica_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table: mysql.%
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Source_Log_Pos: 491750
              Relay_Log_Space: 327499
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Source_SSL_Allowed: Yes
           Source_SSL_CA_File:
           Source_SSL_CA_Path:
              Source_SSL_Cert:
            Source_SSL_Cipher:
               Source_SSL_Key:
        Seconds_Behind_Source: 0
Source_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Source_Server_Id: 387556003
                  Source_UUID: 500ca95d-4e69-3bcb-be09-ada71edf3a0b
             Source_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
    Replica_SQL_Running_State: Replica has read all relay log; waiting for more updates
           Source_Retry_Count: 86400
                  Source_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Source_SSL_Crl:
           Source_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Source_TLS_Version:
       Source_public_key_path:
        Get_Source_public_key: 0
            Network_Namespace:
1 row in set (0.06 sec)
```
`Seconds_Behind_Source: 0`問題なし


### DBインスタンスタイプ変更


- n2rds-develop-onbin-80-crr

`db.m5.large` -> `db.m6g.large`

<img width="1276" alt="Image" src="https://github.com/user-attachments/assets/2b9a0dbb-e9f2-4083-aede-726cf1b9dfac" />

`14:52` -> `15:08`

<img width="1312" alt="Image" src="https://github.com/user-attachments/assets/e76fa15b-b173-4c83-a180-41b5a46de1c4" />

約20分程度

レプリケーション

```
mysql> show replica status\G
*************************** 1. row ***************************
             Replica_IO_State: Waiting for master to send event
                  Source_Host: 172.23.1.141
                  Source_User: rdsrepladmin
                  Source_Port: 3306
                Connect_Retry: 60
              Source_Log_File: mysql-bin-changelog.004720
          Read_Source_Log_Pos: 544
               Relay_Log_File: relaylog.000085
                Relay_Log_Pos: 666
        Relay_Source_Log_File: mysql-bin-changelog.004720
           Replica_IO_Running: Yes
          Replica_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table: innodb_memcache.cache_policies,innodb_memcache.config_options,mysql.plugin,mysql.rds_configuration,mysql.rds_history,mysql.rds_monitor,mysql.rds_replication_status,mysql.rds_sysinfo,mysql.rds_upgrade_prechecks
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Source_Log_Pos: 544
              Relay_Log_Space: 1105
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Source_SSL_Allowed: Yes
           Source_SSL_CA_File:
           Source_SSL_CA_Path:
              Source_SSL_Cert:
            Source_SSL_Cipher:
               Source_SSL_Key:
        Seconds_Behind_Source: 0
Source_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Source_Server_Id: 1815583817
                  Source_UUID: f691ed42-f571-11ef-8ce5-06be67a5a0db
             Source_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
    Replica_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Source_Retry_Count: 86400
                  Source_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Source_SSL_Crl:
           Source_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Source_TLS_Version:
       Source_public_key_path:
        Get_Source_public_key: 0
            Network_Namespace:
1 row in set (0.07 sec)
```

問題なし

- n2rds-develop-plus-80-cluster-crr

Instanceの変更から実施

`db.t3.medium` -> `db.t4g.medium`

<img width="1307" alt="Image" src="https://github.com/user-attachments/assets/42640a72-dbe7-4e6c-9cfc-5db8679012a2" />

`15:43` ~ `15:50`

<img width="1267" alt="Image" src="https://github.com/user-attachments/assets/0a2f07a5-a82e-438a-8cd0-61c826b91bc5" />

レプリケーション

```
mysql> show replica status\G
*************************** 1. row ***************************
             Replica_IO_State: Waiting for source to send event
                  Source_Host: 172.21.15.0
                  Source_User: rdsrepladmin
                  Source_Port: 3306
                Connect_Retry: 60
              Source_Log_File: mysql-bin-changelog.007754
          Read_Source_Log_Pos: 584909
               Relay_Log_File: relaylog.000002
                Relay_Log_Pos: 336
        Relay_Source_Log_File: mysql-bin-changelog.007754
           Replica_IO_Running: Yes
          Replica_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table: mysql.%
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Source_Log_Pos: 584909
              Relay_Log_Space: 539
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Source_SSL_Allowed: Yes
           Source_SSL_CA_File:
           Source_SSL_CA_Path:
              Source_SSL_Cert:
            Source_SSL_Cipher:
               Source_SSL_Key:
        Seconds_Behind_Source: 0
Source_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Source_Server_Id: 387556003
                  Source_UUID: 500ca95d-4e69-3bcb-be09-ada71edf3a0b
             Source_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
    Replica_SQL_Running_State: Replica has read all relay log; waiting for more updates
           Source_Retry_Count: 86400
                  Source_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Source_SSL_Crl:
           Source_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Source_TLS_Version:
       Source_public_key_path:
        Get_Source_public_key: 0
            Network_Namespace:
1 row in set (0.07 sec)
```
